on:
  push:
    branches:
      - 'main'
      - 'develop'
    tags:
      - "v*.*"

name: build & publish

jobs:
  build:
    name: build Linux x86_64
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build:
        - stable-x86
        - stable-arm64
        - stable-armv7
        include:
        - build: stable
          os: ubuntu-22.04
          target: x86_64-unknown-linux-gnu
        - build: stable-arm64
          os: ubuntu-22.04
          target: aarch64-unknown-linux-gnu
        - build: stable-armv7
          os: ubuntu-22.04
          target: armv7-unknown-linux-gnueabi
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: setup rust
        with:
          toolchain: stable
          override: true
      - name: Setup Cross
        if: matrix.target != ''
        run: |
          echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
          echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV
      - uses: actions-rs/cargo@v1
        name: build
        with:
          command: build
          args: -r
